-- MySQL Script generated by MySQL Workbench
-- Tue Mar 16 11:54:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `adlister_db`;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adlister_db` DEFAULT CHARACTER SET utf8;
USE `adlister_db`;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adlister_db`.`users`;

CREATE TABLE IF NOT EXISTS `adlister_db`.`users`
(
    `id`       INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(250) NOT NULL,
    `email`    VARCHAR(250) NOT NULL,
    `password` VARCHAR(250) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE
)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`ads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adlister_db`.`ads`;

CREATE TABLE IF NOT EXISTS `adlister_db`.`ads`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id`     INT UNSIGNED NOT NULL,
    `title`       VARCHAR(250) NOT NULL,
    `description` TEXT(1000)   NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `user_id`
        FOREIGN KEY (`user_id`)
            REFERENCES `adlister_db`.`users` (`id`)
            ON DELETE CASCADE
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adlister_db`.`categories`;

CREATE TABLE IF NOT EXISTS `adlister_db`.`categories`
(
    `id`   INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(250) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`ad_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adlister_db`.`ad_categories`;

CREATE TABLE IF NOT EXISTS `adlister_db`.`ad_categories`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ad_id`       INT UNSIGNED NOT NULL,
    `category_id` INT UNSIGNED NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `ad_id_idx` (`ad_id` ASC) VISIBLE,
    INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
    CONSTRAINT `ad_id`
        FOREIGN KEY (`ad_id`)
            REFERENCES `adlister_db`.`ads` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `category_id`
        FOREIGN KEY (`category_id`)
            REFERENCES `adlister_db`.`categories` (`id`)
            ON DELETE CASCADE
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adlister_db`.`comments`;

CREATE TABLE IF NOT EXISTS `adlister_db`.`comments`
(
    `id`      INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` INT UNSIGNED NOT NULL,
    `ad_id`   INT UNSIGNED NOT NULL,
    `content` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `ad_id_idx` (`ad_id` ASC) VISIBLE,
    INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `ad_id`
        FOREIGN KEY (`ad_id`)
            REFERENCES `adlister_db`.`ads` (`id`)
            ON DELETE CASCADE
            ON UPDATE NO ACTION,
    CONSTRAINT `user_id`
        FOREIGN KEY (`user_id`)
            REFERENCES `adlister_db`.`users` (`id`)
            ON DELETE CASCADE
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `adlister_db`.`images`;

CREATE TABLE IF NOT EXISTS `adlister_db`.`images`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `ad_id`       INT UNSIGNED NOT NULL,
    `url`         VARCHAR(400) NOT NULL,
    `description` VARCHAR(400) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `ad_id_idx` (`ad_id` ASC) VISIBLE,
    CONSTRAINT `ad_id`
        FOREIGN KEY (`ad_id`)
            REFERENCES `adlister_db`.`ads` (`id`)
            ON DELETE CASCADE
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
